name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: "$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
  - title: "✨ New features"
    labels:
      - "new-feature"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
#  - title: "🚀 Enhancements"
#    labels:
#      - "enhancement"
#      - "refactor"
#      - "performance"
#  - title: "🧰 Maintenance"
#    labels:
#      - "maintenance"
#      - "ci"
#  - title: "📚 Documentation"
#    labels:
#      - "documentation"
  - title: "⬆️ Dependency updates"
    collapse-after: 5
    labels:
      - "dependency-update"
#  - title: "🚨🚨 Security Fixes 🚨🚨"
#    labels:
#      - "security"


include-labels:
  - "bugfix"
  - "new-feature"
  - "breaking-change"

no-changes-template: '- No changes'
autolabeler:
  - label: 'bugfix'
    body:
      - '/- \\[x\\] Bugfix (fixed change that fixes an issue)/'
  - label: 'new-feature'
    body:
      - '/- \\[x\\] New feature (thanks!)/'
  - label: 'breaking-change'
    body:
      - '/- \\[x\\] Breaking change (repair/feature that breaks existing functionality)/'
  - label: 'dependency-update'
    body:
      - '/- \\[x\\] Dependency Update - Does not publish/'

      
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/ApolloAutomation/AIR-1_Test/compare/$PREVIOUS_TAG...$RESOLVED_VERSION.1

   Be sure to 🌟 this repository for updates!