name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  label-check:
    name: Label Check
    runs-on: ubuntu-latest
    outputs:
      chosen_label: ${{ steps.determine_label.outputs.chosen_label }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write PR Body to File
        run: |
          echo "Saving the PR body to pr_body.txt..."
          printf '%s\n' "${{ github.event.pull_request.body }}" > pr_body.txt

      - name: Determine Single Label
        id: determine_label
        run: |
          label=""
          # In order, we check each pattern. The first match wins.
          if grep -qE '^- \\[x\\] Bugfix \\(fixed change that fixes an issue\\)' pr_body.txt; then
            label="bugfix"
          elif grep -qE '^- \\[x\\] New feature \\(thanks!\\)' pr_body.txt; then
            label="new-feature"
          elif grep -qE '^- \\[x\\] Breaking change \\(repair/feature that breaks existing functionality\\)' pr_body.txt; then
            label="breaking-change"
          elif grep -qE '^- \\[x\\] Dependency Update - Does not publish' pr_body.txt; then
            label="dependency-update"
          fi

          echo "Chosen label: $label"
          echo "chosen_label=$label" >> $GITHUB_OUTPUT

      - name: Apply Single Label
        if: ${{ steps.determine_label.outputs.chosen_label != '' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.determine_label.outputs.chosen_label }}

  ci:
    name: Building ${{ matrix.file }}
    needs: [ label-check ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - Integrations/ESPHome/PLT-1.yaml
          - Integrations/ESPHome/PLT-1B.yaml
        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v6
        with:
          yaml-file: ${{ matrix.file }}